### ISSUE TITLE
Please, Can you assist, I am working a research project using log files from AM/3D printing machines

### ISSUE THREAD

**Issue by micalabs** [logpai/loglizer#11]
Dear Sir/Ma.

Please, I am currently writing a paper, 'using machine learning techniques for Anomaly Detection in Additive Manufacturing/3D Printing Log Files'. The data was collected via Additive Manufacturing/3D printing machines. And it is totally a log files. I didn't know how to extract useful features from the data before applying machine learning algorithm. I believe your open source code was in Python. Is it compulsory to use log parser to extract the valuable features, or is there any other way to extra useful data from the log file. or can I use it directly. Another question will your source code in python be suitable for this type of my study?

Below is the sample of the log files collected:

Wed 04/25/18 11:44:26 DEBUG    NOTICE         0 NextSubState: CHECK_PLATFORM_STATE -> WAIT_CONFIRM_PLATFORM_STATE
Wed 04/25/18 11:44:26 DEBUG    NOTICE         0 Setting resolution mode to (PP) 2
Wed 04/25/18 11:44:26 DEBUG    NOTICE         0 LoadBuildStyle(): leaving isVerifySupport and isVerifyPart unchanged, both set to FALSE, strStyleName= UHD COLUMN
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: UHD COLUMN
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: style file:    ..\data\BuildStyles_HD_3500_Plus.ini
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: params:       ..\data\Param_HD_Plus_UHD_TaiPan.ini
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: common:       ..\data\Common_TAIPAN.ini
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: calibration:  ..\data\Calibration_656dpi.ini
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: machine:      ..\data\Machine.ini
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: support type: original
Wed 04/25/18 11:44:26 DEBUG    PARAM_CHANGE    0 LoadBuildStyle: support:      C:\ProJet\Bin\..\data\fill_HiRes_TaiPan.dct
Wed 04/25/18 11:44:26 DSP      LOG             0 SetResolutionMode : 2
Wed 04/25/18 11:44:26 DSP      LOG             0 Changed passes to 20
Wed 04/25/18 11:44:27 DEBUG    NOTICE         0 Read and updated ini parameters.  Cure Passes = 10
Wed 04/25/18 11:44:27 DEBUG    NOTICE         0 Send Parameters To DSP
Wed 04/25/18 11:44:27 DEBUG    NOTICE         0 Setting resolution mode to (PP) 2
Wed 04/25/18 11:44:27 PREP     IDLE              0 Max Files=25, Params=9999
Wed 04/25/18 11:44:27 PREP     CTL_INITIALIZE    2 Input File: C:\ProJet\Bin\..\work\jobs\Job642_2018-4-25_11-36-592\parts.ctl, Support Type: ORIGINAL, Minimum Supports: 0.110000
Wed 04/25/18 11:44:27 DSP      LOG             0 SetResolutionMode : 2
Wed 04/25/18 11:44:27 DSP      LOG             0 Changed passes to 20
Wed 04/25/18 11:44:34 DEBUG    BTN_PRESSED   11 Yes Pressed
Wed 04/25/18 11:44:34 DEBUG    NOTICE         0 NextSubState: WAIT_CONFIRM_PLATFORM_STATE -> AFTER_CLOSE_CHAMBER_DOOR_STATE
Wed 04/25/18 11:44:36 DEBUG    NOTICE         0 NextSubState: AFTER_CLOSE_CHAMBER_DOOR_STATE -> CHECK_WASTE_STATE
Wed 04/25/18 11:44:40 DEBUG    NOTICE         0 NextSubState: CHECK_WASTE_STATE -> WAIT_CLOSE_WASTE_DRAWER_STATE_SHARK_ENTRY_POINT
Wed 04/25/18 11:44:40 DEBUG    NOTICE         0 NextSubState: WAIT_CLOSE_WASTE_DRAWER_STATE_SHARK_ENTRY_POINT -> AFTER_CLOSE_WASTE_DRAWER_STATE
Wed 04/25/18 11:44:41 DEBUG    NOTICE         0 NextSubState: AFTER_CLOSE_WASTE_DRAWER_STATE -> WAIT_CLOSE_WASTE_DRAWER_STATE

**Comment by ShilinHe** [comment]
I suggest you read our paper, it shows how the entire process of log analysis with machine learning. The logs should be parsed firstly, and a sequence of logs should be built into event count vectors(feature extraction) before feeding into a machine learning model.

**Comment by elieser1101** [comment]
hello @micalabs , i would like to help you in your research, if you are interested please email me at elieser.pereira@gmail.com, i've been working with this code and would like to try with real data
