### ISSUE TITLE
More info needed

### ISSUE THREAD

**Issue by sharanbr** [logpai/loglizer#12]
Can you update readme to indicate which Python file is used for what purpose. There are many Python files and it is not clear what is the purpose of each of these

**Comment by ShilinHe** [comment]
Thanks for your suggestion! We will update the Readme or add a Document soon or late.

**Comment by sharanbr** [comment]
Dear Shilin,

I need one more input. I am trying to run classifier_bgl file. Python shows
error with respect to the data file.
IOError: File ../../Data/BGL_data/BGL_MERGED.log does not exist

Do I need to download any data file? Is BGL_MERGED.log an input or an
output file?

Can you give some directions?

**Comment by ShilinHe** [comment]
The hdfs and bgl are two log datasets that we used in our paper, and you can find them in the loghub project (https://github.com/logpai/loghub). You may request the datasets as introduced in the Readme

**Comment by sharanbr** [comment]
Hi Shilin,

I have downloaded the dataset at loghub. Do I need to rename any files to
run your code?
I see that classifier_bgl looks for BGL_MERGED.log but I don't see such a
file in the downloaded dataset.
Do I need to rename BGL_2k.txt as BGL_MERGED.log and move it to BGL_DATA
directory?

Also, do you know if anyone has successfully run these code before?

**Comment by ShilinHe** [comment]
BGL_2k is just a small sample, you should request the full datasets through the link in Readme file.

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. We will also release the benchmark code soon. @sharanbr
