### ISSUE TITLE
training a new log parser

### ISSUE THREAD

**Issue by GennaroOpen1981** [logpai/loglizer#15]
Hello, 

is it possible to train the system with my own device logs?

Thanks

**Comment by jagadeesanm-jag** [comment]
I am also interested to train the dataset or make use of unsupervised models . whether it is possible ?

**Comment by jagadeesanm-jag** [comment]
Thanks ShilinHe . By any chance it is possible to share the paper to this email id jagadeesan.m@gmail.com . I don't have the access to paper . This could be great help . 

Thanks in Advance !!!

**Comment by ShilinHe** [comment]
Please check the email

**Comment by GennaroOpen1981** [comment]
Hello Shilin HE,

could you please send it to me also via email at gen.marrazzo@gmail.com?

Thanks in advance

Regards


Il giorno dom 11 nov 2018 alle ore 09:49 Shilin HE <notifications@github.com>
ha scritto:
