### ISSUE TITLE
vectorization

### ISSUE THREAD

**Issue by zhou18** [logpai/loglizer#19]
I did log parsing and have HDFS_2.log_structured.csv.
now how can i get rm_repeat_rawTFVector.txt (log sequence file) by vectorization based on block-id?

**Comment by jimzhu** [comment]
yes. based on blk id

**Comment by zhou18** [comment]
Could you please help me how can i do it? do you have any reference for doing this task?

**Comment by F-SLoong** [comment]
> Could you please help me how can i do it? do you have any reference for doing this task?

Do you find the log sequense file?

**Comment by ShilinHe** [comment]
Logs that have the same block_id should be grouped together. Then, according to the occurrence number of each log event, we can build the event count vector to represent the vectorization form of a log sequence.  That is, each dimension shows a log event, and the occurrence number is the corresponding value of that dimension.
