### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by zhou18** [logpai/loglizer#21]
hi, when I run PCA_hdfs.py I got this error for this line of data_loader.py:(can not load label file)
line 32
label_df = pd.read_csv(label_path, delimiter=r'\s+', header=None, usecols = [0], dtype =int) # usecols must be a list

error
  File "pandas/_libs/parsers.pyx", line 1162, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: invalid literal for long() with base 10: 'BlockId,Label'

**Comment by ShilinHe** [comment]
Block ID should not be included in the input matrix. The block ID is in string type.
