### ISSUE TITLE
mining_invariants

### ISSUE THREAD

**Issue by Spuro85** [logpai/loglizer#25]
in mining_invariants.py

a. what is "scale_list" in list para? Why "scale_list": 1,2,3?

b. 

```
def check_invar_validity(para, event_count_matrix, selected_columns):
 
    .....   

1.     min_theta, FLAG_contain_zero = compute_eigenvector(sub_matrix)
2.     abs_min_theta = [np.fabs(it) for it in min_theta]
3. 	 if FLAG_contain_zero:
4. 		return validity, [];
5. 	else:
6.              for i in para['scale_list']:
7. 			min_index = np.argmin(abs_min_theta)
8. 			scale = float(i) / min_theta[min_index]
9. 			scaled_theta = np.array([round(item * scale) for item in min_theta])
10. 			scaled_theta[min_index] = i
11. 			scaled_theta = scaled_theta.T
12. 			if 0 in np.fabs(scaled_theta):
13. 				continue
14. 			dot_submat_theta = np.dot(sub_matrix, scaled_theta)
```

what is the meaning of vector "min_theta" transformations in rows 7-10?
0 not in "abs_min_theta" consequently 0 not in "scaled_theta", why condition in row 12?

**Comment by ShilinHe** [comment]
a. Please refer to the original paper, mining invariants by Lou et al, for more details.
b. Because we need to scale the original value into integers. 
If I remember it correctly, row 12 is used to handle the corner case led by the precision of those Python variables.
