### ISSUE TITLE
A question about 'Feature Extraction' in PCA.

### ISSUE THREAD

**Issue by 399050934** [logpai/loglizer#27]
Hi~ After reading your paper about log parsers and log anomolies detection, it is so helpful for my study especially your toolkit. Thanks a lot!
Here I have a question about PCA: I have read the paper of PCA method, and I know what's meaning  of the files 'rm_repeat_rawTFVector.txt' and 'rm_repeat_mlabel.txt'. But it seems that there is not any method generating those files. They are belong to the phase of 'Feature Extraction', but I do not find any method about generating them. I also check the toolkit of log parsers, and I also cannot find such method. Hope that you can answer my question~ Thanks very much!

**Comment by jimzhu** [comment]
There is a gap between different versions of data and the code. We will fix it by this weekend,

**Comment by 399050934** [comment]
Thanks~ I think that how to get those files is more important in PCA, cause it is the core of PCA in my opinion.

**Comment by jimzhu** [comment]
We have a quick reference for the input data. Pls check the FAQ in README.

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. @399050934
