### ISSUE TITLE
How to use loglizer?

### ISSUE THREAD

**Issue by cfl2005** [logpai/loglizer#29]
Hi,
I have just started researching log anomaly detection recently. I am very interested in your results. I have the following questions, please also guide me.
1.How should I use the results of the logparser operation in loglizer?
'path':'../../Data/SOSP_data/', # directory for input data
'log_seq_file_name':'rm_repeat_rawTFVector.txt', # filename for log sequence data file
'label_file_name':'rm_repeat_mlabel.txt', # filename for label data file
(1)'path' data is log_structured.csv?or log_templates.csv?
(2)Where can I find 'rm_repeat_rawTFVector.txt and 'rm_repeat_mlabel.txt?
2.In demo_bgl, the input parameters are log_file_name and log_event_mapping and in demo_hdfs ,the input parameters are log_seq_file_name and label_file_name. Do you mean to support these two parameter input methods?
Thank you very much, look forward to your reply！

**Comment by jimzhu** [comment]
The Demo from parsing to anomaly detection is still in progress, We will update it Recently.

**Comment by abdelhadi-azouni** [comment]
Hi, thanks for sharing the code.
I have the same question, cannot find the input files and how to generate them
Thanks

**Comment by jimzhu** [comment]
We have a quick reference for the input data. Pls check the FAQ in README.

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. @abdelhadi-azouni @cfl2005
