### ISSUE TITLE
Suggestions for collecting logs

### ISSUE THREAD

**Issue by thatcher** [logpai/loglizer#3]
Hi, looking forward to trying your project!  Its a great fit because we have millions of lines of apache logs per day (not including our local edge caching and cdn caching), we are an all python shop, and we get hit by malicious bots randomly that do impact our public experience.

Im trying to figure out the collection piece of the equation, whether its for adhoc exploration for a specific range of dates or if its on going collection for feeding loglizer.

Do you have any suggestions?

Thanks
Thatcher

**Comment by ShilinHe** [comment]
Sorry for the late reply.
If I understand your question correctly, it is about whether the logs are continuously collected or just collected during a period? Actually, in our setting, we use logs collected during a time period, based on which we do the analysis.

**Comment by thatcher** [comment]
Thanks for the reply! My question is more about how you collect logs for analysis.  Right now I’m working on a fabric script that does it over ssh, tars up a date range of access logs and then we scp it to the host we use to process them.  I was just curious how you gather up the logs for processing?

Thanks!
Thatcher

**Comment by ShilinHe** [comment]
Logs are often collected from a distributed system (e.g., HDFS)/online service system or other systems.  These systems collect the logs automatically and save into log files. For anomaly detection, these logs record the execution of tasks (multiple logs record one task). For the access logs, if each of them is independent of each other, I think the anomaly detection cannot be applied here. You may refer to our papers for details.

**Comment by jimzhu** [comment]
@thatcher Thanks for your interest! For trying out our current models on anomaly detection, we suggest collecting a batch of logs over a period. But if you are interested in deploying anomaly detection models online, we suggest using the popular log collection frameworks like Flume/Logstash + Kafka. Then log messages can be analysed in a streaming manner.
