### ISSUE TITLE
Nex Steps

### ISSUE THREAD

**Issue by elieser1101** [logpai/loglizer#35]
i have some time working with your solution, and after some struggle i was able to use your code.  As i read the issues i saw that many people had the same problem.

In that order i make a wrapper that allows me to use the framework with one configurable class as a more friendly API.

I would like to know if you would be interested in a pull request??, so i can clean my code and contribute to your project.

---

In other hand, i would like to know about the future of the project, would you like some help to make this tool more user friendly?

Also i think there is a need to add some unitesting and other automation if you woul like to make this more reliable!

**Comment by jimzhu** [comment]
Thank you very much for your interest in our tool. We will greatly appriciate your contributions (pr or docs) if you would like to.
