### ISSUE TITLE
error in implementation of loglizer.dataloader.load_HDFS function

### ISSUE THREAD

**Issue by josehur** [logpai/loglizer#36]
in this function, you are returning in line 115 **x_data** (whole data set). 
`return (x_data, None), (x_test, None)`

Instead, you are supposed to return 
`return (x_train, None), (x_test, None)`.

Can you confirm please if this is actually an issue?

Thanks a lot for your work.

**Comment by jimzhu** [comment]
@josehur  Thanks for reporting the bug! We fix it soon.

**Comment by jimzhu** [comment]
It has been fixed. Thanks!
