### ISSUE TITLE
ValueError: shapes (16,16) and (14,) not aligned: 16 (dim 1) != 14 (dim 0)

### ISSUE THREAD

**Issue by frjhong** [logpai/loglizer#37]
I use PCA_demo.py and change train_ratio to 0.8 to train model.
	  
	(x_train, y_train), (x_test, y_test) = dataloader.load_HDFS(struct_log,
                                                                label_file=label_file,
                                                                window='session', 
                                                                train_ratio=0.8,
                                                                split_type='uniform')												
After finishing the training, I dump the model and want to use it to predict.Because for prediction, I lowered the train_ratio to 0.3 to generate the test data and then encountered ValueError: shapes.
If all follow-up data is to be used for prediction, how to generated data in model.predict format?
	
	(x_train, y_train), (x_test, y_test) = dataloader.load_HDFS(struct_log,
                                                                label_file=label_file,
                                                                window='session', 
                                                                train_ratio=0.3,
                                                                split_type='uniform')
    feature_extractor = preprocessing.FeatureExtractor()
    x_train = feature_extractor.fit_transform(x_train, term_weighting='tf-idf', 
                                              normalization='zero-mean')
    x_test = feature_extractor.transform(x_test)

    with open('pca.pickle', 'rb') as f:
		model = pickle.load(f)
	model.predict(x_test[0:100])

pwrai@ab434bffe3be:~/loglizer/loglizer$ python ../demo/PCA_demo3.py
====== Input data summary ======
Total: 7940 instances, 313 anomaly, 7627 normal
Train: 2381 instances, 93 anomaly, 2288 normal
Test: 5559 instances, 220 anomaly, 5339 normal

====== Transformed train data summary ======
Train data shape: 2381-by-14

====== Transformed test data summary ======
Test data shape: 5559-by-14

Traceback (most recent call last):
  File "../demo/PCA_demo3.py", line 33, in <module>
    print(model.predict(x_test[0:100]))
  File "../loglizer/models/PCA.py", line 93, in predict
    y_a = np.dot(self.proj_C, X[i, :])
ValueError: shapes (16,16) and (14,) not aligned: 16 (dim 1) != 14 (dim 0)
pwrai@ab434bffe3be:~/loglizer/loglizer$

**Comment by jimzhu** [comment]
If you need to dump the model, you should also dump feature_extractor. The same feature extrator need to be used during prediction to keep the same dimension of features and the same preprocessing process. Please check https://github.com/logpai/loglizer/blob/master/demo/InvariantsMiner_demo_without_labels.py for the demo.
