### ISSUE TITLE
To teach students on Unsupervised Machine learning based Log Analysis

### ISSUE THREAD

**Issue by hraokr** [logpai/loglizer#38]
Sir
 I am Asst. prof, i have chosen Big Data as subject for this semester and the learning methodology i have selected is "learn by doing", hence I kindly request you guide me in demonstrating a project on "Unsupervised Machine learning based Log Analysis" as i am new to this field and also i would like persuasive further in this subject.
thanking you 
with warm regards
Hanumantha Rao K R
Assistant Professor
Dept. of Computer Applications
JSS Academy of Technical Education
c 20 / 1, sector 62, NOIDA, 201301, U. P , INDIA

**Comment by jimzhu** [comment]
Thanks for your interest and we are glad to provide any support if possible.
