### ISSUE TITLE
interpretation of Invariants mining result

### ISSUE THREAD

**Issue by Rufaida94** [logpai/loglizer#41]
I am having a problem understanding the meaning of the invariants mining results. For example, in the demo:

Invariant space dimension: 11
Mined 10 invariants: {(1, 13): [1.0, -1.0], (3, 11): [-2.0, 1.0], (0, 12): [-10.0, 1.0], (1, 8): [-1.0, 1.0], (3, 9): [-101.0, 1.0], (1, 6): [1.0, -3.0], (1, 10): [-1.0, 1.0], (3, 7): [1.0, -1.0], (3, 4): [1.0, -1.0], (0, 2): [1.0, -1.0]}

I thought the pair (0, 12): [-10.0, 1.0] means that whenever event 12 happens once event 0 has to happen 10 times. but it doesn't make any sense because the HDFS data does not have any event with ID 0 or 12.

**Comment by jimzhu** [comment]
The event id in structured log is 1-started.  But in python implementation, we use 0-started.

**Comment by Rufaida94** [comment]
Can you explain by example, please?
For example in your structured HDFS data the first EventID is E5, but I can't find anything in the output that points to E5. what represents E5 in this output:

Invariant space dimension: 11
Mined 10 invariants: {(1, 13): [1.0, -1.0], (3, 11): [-2.0, 1.0], (0, 12): [-10.0, 1.0], (1, 8): [-1.0, 1.0], (3, 9): [-101.0, 1.0], (1, 6): [1.0, -3.0], (1, 10): [-1.0, 1.0], (3, 7): [1.0, -1.0], (3, 4): [1.0, -1.0], (0, 2): [1.0, -1.0]}
