### ISSUE TITLE
Analyzing generic logs with loglizer

### ISSUE THREAD

**Issue by kokonguyen191** [logpai/loglizer#42]
Hi, thank you very much for working on this project. I have been trying out some of the frameworks in logparser and loglizer but I have yet to get a decent result for my use case. I figure I should at least ask for some opinions before proceeding with my research because it's a lot of work and I don't have a lot of time left.

My logs data is from Jenkins so it's mostly generic data and come from different sources but for now, I'm restricting my data to a single source so the data should be quite similar across all files. So I have a list of log files for different builds and I know which contain failures and which don't. However, I don't know which exact lines show the failure, I only know that there exists such lines in a failure log file. The logs are also quite long, sometimes reaching 30k+ lines per build, and there are several hundred builds.

According to previous work on my dataset, the errors can vary quite a bit, some examples are:

- python exception with the full traceback in the log
- network failure with repeating retry patterns in the log
- unit tests fail with some type of string indicator ("UNIT TEST xx FAIL", "FAILURE AT UNIT TEST xx", etc.) in the log
- github failure (merge conflict, etc.) indicated by string indicators written by the engineers

These are some of the errors I got from matching regex and there are potentially more that I don't know about.

So this is the question I want to ask: it would be the ideal outcome if I can get the error classification right from the log but for now, I settle for an easier question: **how should I approach this problem if I want to get the line / cluster of lines that potentially display the error of a log file?** Currently I'm doing parsing with Drain and analysis with InvariantsMiner, vectorizing using sliding window of size 25, but the train time is too long and the accuracy I got was abysmal.

Any kind of suggestions is appreciated, thank you.

**Comment by kokonguyen191** [comment]
In case anyone in the future find this post and wonder what I did, I parsed my logs with Drain, messed around a little with the hyperparameters, generated log sequences using a sliding window (I used size 5), ran [DeepLog](https://github.com/wuyifan18/DeepLog) on logs that are normal, predicted abnormal behaviour using the sample from the same [DeepLog repo](https://github.com/wuyifan18/DeepLog)

**Comment by ShilinHe** [comment]
Hi @kokonguyen191 , Good to hear that you have figured it out! We sincerely apologize for the late replay since our project members were rushing some deadlines in the last week. Regarding your post, I think you are on the right way. Since there is no indicator such as job id to help separate the logs into a number of instances, a natural choice is using the time window. I found that you are using a fixed window size instead of a fixed window of a specific time period (e.g., 1 hour),  it might be problematic since it could separate a normal user activity into several parts.

**Comment by kartikeyporwal** [comment]
Hi @kokonguyen191, I thank you for sharing what worked for you.

I could parse `.log` files into `.csv` files with suffix `_structured ` and `_template` using [Drain](https://github.com/logpai/logparser/blob/master/demo/Drain_demo.py) by changing necessary paths and `logs_format`.
Here, `_structured.csv` file contains data order by time along with few other columns like EventTemplate, EventId etc. and  `_templates.csv` contains eventid with its respective template.

But, I could not get what you mean by generate log sequences using a sliding window.
Also, [DeepLog](https://github.com/wuyifan18/DeepLog) requires the log files in numerical format. 

What should be my approach?


Any kind of suggestions is much appreciated. Thank You.

**Comment by kartikeyporwal** [comment]
Hi @kokonguyen191, I thank you for sharing what worked for you.

I could parse `.log` files into `.csv` files with suffix `_structured ` and `_template` using [Drain](https://github.com/logpai/logparser/blob/master/demo/Drain_demo.py) by changing necessary paths and `logs_format`.
Here, `_structured.csv` file contains data order by time along with few other columns like EventTemplate, EventId etc. and  `_templates.csv` contains eventid with its respective template.

But, I could not get what you mean by generate log sequences using a sliding window.
Also, [DeepLog](https://github.com/wuyifan18/DeepLog) requires the log files in numerical format but csv files generated by Drain contains Content and Template in string format. How to convert csv file's string to processed file containing numbers in rows for DeepLog?

What should be my approach?


Any suggestions is much appreciated. Thank You.

**Comment by shoaib-intro** [comment]
have you found solution?
