### ISSUE TITLE
benchmark dataset HDFS.npz???

### ISSUE THREAD

**Issue by rajaranjith** [logpai/loglizer#43]
..\loglizer\data\HDFS could not find the "HDFS.npz" in the data path to run the benchmark dataset? where can we get the file?

Thanks in advance...

-Ranjith G

**Comment by ShilinHe** [comment]
Please refer to the loghub project (https://github.com/logpai/loghub)

**Comment by jimzhu** [comment]
The HDFS.npz is the structured ndarry data transformed from HDFS_structured.csv. It has been uploaded to loghub (via Zenodo). You can download it there. @rajaranjith

**Comment by rajaranjith** [comment]
I couldn't get it in loghub..npz files are not there.

Sent from Yahoo Mail on Android 
 
  On Fri, 24 May 2019 at 20:45, Jamie Zhu<notifications@github.com> wrote:   
The HDFS.npz is the structured ndarry data transformed from HDFS_structured.csv. It has been uploaded to loghub (via Zenodo). You can download it there. @rajaranjith

**Comment by jimzhu** [comment]
You need request the data access through Zenodo link there.

**Comment by dineshb302** [comment]
But the Zenodo link only provide raw data, I need HDFS.npz processed

**Comment by jimzhu** [comment]
When did you access the loghub datasets? It was uploaded about 3 months ago.

**Comment by dineshb302** [comment]
Hi I tried today only, I could only find
HDFSlog2k there , but not this HDFS.npz. Can you give me exact url of file
, if i am missing something ?

**Comment by jimzhu** [comment]
please follow the loghub reademe to submit your request via zenodo

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jimzhu** [comment]
please follow the loghub reademe to submit your request via zenodo
