### ISSUE TITLE
Invariants mining broken invariants

### ISSUE THREAD

**Issue by Rufaida94** [logpai/loglizer#45]
I am using the invariants mining tool for anomaly detection, right now I want to print out the list of broken invariants if possible to see if the results make sense or not. or at least print the log sequences that have anomalies in them. is this do-able right now? and if yes, what should I do? 
thanks

**Comment by ShilinHe** [comment]
Yes, you can do that by print out the line [when predicting the anomaly](https://github.com/logpai/loglizer/blob/79e0a3f55b29705cd7a58ee500696d41f8ec23e3/loglizer/models/InvariantsMiner.py#L69). If it equals to 1, then this log instance is an anomaly and you can recover the original log messages accordingly.
