### ISSUE TITLE
Where does the structured.csv comes from

### ISSUE THREAD

**Issue by ai2010** [logpai/loglizer#46]
Hello,

I would like to know which raw file produces the structured csv file  in  	data/HDFS and which parser algo has been used if you don't mind.
Thanks

**Comment by jimzhu** [comment]
It's generated from the raw log with the templates provided in logparser/logs/HDFS. We use demo/logmatch_demo for quick matching and pick the first 100k lines.

**Comment by ai2010** [comment]
thanks for your reply. However in that folder logparser/logs/HDFS, there is not a log file with 100k lines or more. Where is it the log file from which you apply the  demo/logmatch_demo coming from?

**Comment by jimzhu** [comment]
The raw log data can be requested via Zenodo. Details are available at logpai/loghub
