### ISSUE TITLE
Loglizer metrics with PCA

### ISSUE THREAD

**Issue by psychogyiokostas** [logpai/loglizer#47]
Hello,

Using loglizer/data/HDFS/HDFS_100k.log_structured.csv file as the structured data set and the anomaly_label.csv from the same path, i run PCA_demo.py with the same parameters as yours for the dataloader.py (for the train/test split).

The results i got for this case are here:

![image](https://user-images.githubusercontent.com/32713861/60989515-2248b180-a33e-11e9-8d61-6af1f3cb517d.png)

We see that recall metrics don't match. Is there something i am missing? 

Thank you in advance.

**Comment by jimzhu** [comment]
The results we provided are run over the entire dataset. In case you want to reproduce it, pls run the script in benchmark. The raw datasets can be obtained at loghub.

**Comment by psychogyiokostas** [comment]
Thank you for the reply. I requested access.
