### ISSUE TITLE
How to generate the graph ?

### ISSUE THREAD

**Issue by sunilsjb** [logpai/loglizer#49]
Thanks for the details, it helps a lot.
But if I want to generate a graph to illustrate the algorithm how can I do it with help of EventID.
To generate the graph we need to have n x 2 (where n is row and 2 is column), with the logic we will have n x m and with that I need to know how can we generate the graph.

Correct me If I'm wrong.

**Comment by amineebenamor** [comment]
Which algorithm do you want to illustrate?

**Comment by sunilsjb** [comment]
I want to illustrate SVM

**Comment by jimzhu** [comment]
I don't understand what graph you are saying. @sunilsjb
