### ISSUE TITLE
Run the project Loglizer

### ISSUE THREAD

**Issue by melvinmoses123** [logpai/loglizer#5]
I'm new to python and machine learning. I want to know how  to run this project 

> https://github.com/logpai/loglizer
in this link. Plus can I get any full documentation of the entire project. Any help would be appreciable.

**Comment by melvinmoses123** [comment]
Hi,
   In all demo files parameters are there like below.

para={
'path':'../../Data/BGL_data/', # directory for input data
'log_file_name':'BGL_MERGED.log', # filename for log data file
'log_event_mapping':'logTemplateMap.csv'....
}

I think the codes are written for the contents of the "log_file_name" in
the parameter list. But the problem facing was I can't found the log files
in your repository. Can you please direct me to get the sample logs
(BGL_MERGED.log") mentioned in your parameter list.

Thanks
Melvin Moses

**Comment by ShilinHe** [comment]
Hi there, the datasets are available at https://github.com/logpai/loghub.
Among them, one dataset from Blue Gene/L system is the one we use. The address is https://www.usenix.org/cfdr-data

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. @melvinmoses123
