### ISSUE TITLE
event count matrix for bgl data

### ISSUE THREAD

**Issue by bozhang213** [logpai/loglizer#51]
Hi thanks for open source your code. When I try to produce the event count matrix for bgl data, I found the method (bgl_preprocess_data) in your loglizer/loglizer/dataloader.py file and I got similar F-measure using this method.  However, I found a problem in lines 232-233 (`if label_data[k]: label = 1`). If I'm right, these two lines are to label the windows. But this two lines will label all the windows to 1 (anomaly) except those windows containing no events. From the description of bgl data, I think "-" should indicate normal logs.

**Comment by jimzhu** [comment]
The bgl_preprocess_data is the original implementation of our ISSRE paper. But it has not been updated to our new interface. It is correct that "-" should indicate normal logs.
