### ISSUE TITLE
How to load log data in sliding window

### ISSUE THREAD

**Issue by xinyangjijia** [logpai/loglizer#52]
Now we need to process a batch of logs.We want to load this data in sliding window.
But in your file named dataloder.py,  the function (load_BGL)  is TODO.
We want to know if this function has been completed.And if completed, can you provide a source code to us?
We need your help.thanks.

**Comment by jimzhu** [comment]
bgl_preprocess_data() in dataloader is our previous implemention. You can use it for your reference. We currently have no new implementation yet.

**Comment by Zakaria-laktati** [comment]
Can we have an implementation (or just a template) of unlabeled data in sliding window please !
