### ISSUE TITLE
How to report the anomaly sequence

### ISSUE THREAD

**Issue by Wapiti08** [logpai/loglizer#55]
Hi Guys:

I have used the PCA.py to get the following results:
Total: 7940 instances, 313 anomaly, 7627 normal
Train: 3969 instances, 156 anomaly, 3813 normal
Test: 3971 instances, 157 anomaly, 3814 normal

I am considering how to print out the anomaly sequence or even the original log for processing and analysing. I checked the program, it says you need to check manually. Has it been reality to achieve the function I mentioned above? Or I need to figure it out by myself.

**Comment by jimzhu** [comment]
If you need the target anomaly sequence, you need to print the variables in the program for that.

**Comment by Wapiti08** [comment]
In fact, i print it out. But it does not make sense. It is normalized sequence. I was considering whether i can print out the original log or just the log key.

**Comment by jimzhu** [comment]
Did you figure it out? You need to keep the orginal eventID in data loader.

**Comment by Wapiti08** [comment]
Yeah. I saved the dict with ID and really log and enable to report with really anomaly logs. Really thankful for your reply and helps.

**Comment by jimzhu** [comment]
Nice to know that. Could you please share your code for this with a pr?

**Comment by Wapiti08** [comment]
Sorry, I just check the message. 
Not sure whether it is what you want, you saved the xx_sliding_24h_3h.csv file before.
I just find the anomaly index in that file and trace back through this file.

**Comment by Wapiti08** [comment]
I may not be able to share all files. While I will copy the core part for you. Hope it would be helpful. By the way, I think you can easily achieve that.

    for x,y in zip(x_test_original, y_test):
        x_y_dict[str(x)+','+str(i)] = y_test
        i += 1
    # print("the result is:", len(y_test))
    # print("the key names are:", x_y_dict.keys())
    # get the indexs of anomaly sequences
    anomaly_sequence_index = [i for i in range(len(y_test)) if y_test[i] == 1]
    print("the index of anomaly sequence is:", anomaly_sequence_index)

    # trace the index in the sliding_file_path
    sliding_file_path = '../../Dataset_ML/Linux_mal_sliding_24h_3h.csv'
    for index in anomaly_sequence_index:
        # read sliding file: start_end_index
        fd = pd.read_csv(sliding_file_path, header = None)
        start_index, end_index = None, None
        # get the start and end time from index value
        start_index = fd.iloc[index,:][0]
        end_index = fd.iloc[index,:][1]
        print("please check log csv indexes between {} and {}".format(start_index, end_index))

**Comment by Wapiti08** [comment]
I will pull it soon. Hope it will be helpful.

**Comment by jimzhu** [comment]
Many Thanks!
