### ISSUE TITLE
Invariant Mining with Drain

### ISSUE THREAD

**Issue by damucka** [logpai/loglizer#6]
Hello Colleagues,

Thank you for your work, I really appreciate it. 

At the moment we are in the stage of evaluation of different approaches to analyze the logs (SAP HANA database) and search for anomalies in it. After reading your paper I would like to start deploying two of your approaches:
- Invariant Mining
- Decision Tree

Before that however, I would like to confirm that my thinking is correct:
- The input to the algorithms should be the parsed log events. You referred in your paper to the logparser as a possible way to go. Looking at the accuracy of different logparser algorithms, I would pick the Drain to go first. 
--> Would the output of the logparser-Drain be a proper input to the loglizer algorithms (Invariant Mining / Decision Tree)?
Or are there any intermediate steps needed?

Kind Regards,
Kamil Damuc

**Comment by ShilinHe** [comment]
Yes, currently those parsers (https://github.com/logpai/logparser) provided by us can achieve a high accuracy. After parsing, the event count vector should be built (details can be found in the paper). Finally, those vectors could be fed into the machine learning models.

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos, which fix your problems clearly. @damucka
