### ISSUE TITLE
请问LogClustering的使用过程中标注数据是必须的吗

### ISSUE THREAD

**Issue by zeffon** [logpai/loglizer#62]
请问在使用LogClustering的时候，在没有标注数据的情况下也是可以使用的吗？因为现在手头很多数据都是没有标注的

**Comment by zeffon** [comment]
> 无标注情况下，无法知道哪些类是有问题的，如果确实没办法，可以认为小类比较有可能有问题
@ShilinHe 
非常感谢抽空回答问题，然后还有一点想确认一下。
请问InvariantsMiner_demo_without_labels和PCA_demo_without_labels就可以直接使用没有标注数据进行处理对吧？

**Comment by jimzhu** [comment]
是的。同时，因为没有label，最后并没有进行准确度评估。label只是在评估时使用
