### ISSUE TITLE
Missing Log-event mapping - log sequence data

### ISSUE THREAD

**Issue by vovandaihai** [logpai/loglizer#8]
Hi, thank for your project. It really helpful.
I'm trying run loglizer, but have problem with log event mapping (for case demo bgl) and log sequence data (for case demo hdfs). After I run success logparser, output include templates.txt contain all templates and difference text files contain log ID. It's good with your describe in README file. So how can I generate 2 missing files? 
Thank you.

**Comment by ShilinHe** [comment]
To build the log sequence data, please refer to our paper, where we introduced three vectorization methods, sliding window, fixed window, and by the identifier. 
The log-event mapping actually is a file which contains two columns, the first column is all the logs, and the second column is its event id. The file is only used for quick indexing.

**Comment by vovandaihai** [comment]
Thank you, I'll follow your guide.

**Comment by vovandaihai** [comment]
Thank you, I'll follow your guide.
