### ISSUE TITLE
PCA.py

### ISSUE THREAD

**Issue by Yao-fighting** [logpai/loglizer#9]
Hi,
Thanks for your project. It's really helpful.
But I feel confused about 'c_alpha' in PCA.py. How to determine the value? I find it was 3.2905 before. Currently it is 8.1. 
Thank you.

**Comment by ShilinHe** [comment]
It should be 3.2905 if we want to keep 95% of the variance (set by the parameter fraction). The value should follow a fixed statistic/distribution table, distribution function table or something like that.

**Comment by Yao-fighting** [comment]
Do you have more information about this table? or some paper about it? What's the relationship between this value and the variance ratio?
Thanks.

**Comment by ShilinHe** [comment]
There is one such table, but I forget the exact name, maybe you could google it. The relation between the value and the variance ratio should be a one-to-one mapping.
